// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PluginToBot/BotActivity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SCPDiscord.Interface {

  /// <summary>Holder for reflection information generated from PluginToBot/BotActivity.proto</summary>
  public static partial class BotActivityReflection {

    #region Descriptor
    /// <summary>File descriptor for PluginToBot/BotActivity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BotActivityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1QbHVnaW5Ub0JvdC9Cb3RBY3Rpdml0eS5wcm90bxIUU0NQRGlzY29yZC5J",
            "bnRlcmZhY2Ui1gIKC0JvdEFjdGl2aXR5EjwKCnN0YXR1c1R5cGUYASABKA4y",
            "KC5TQ1BEaXNjb3JkLkludGVyZmFjZS5Cb3RBY3Rpdml0eS5TdGF0dXMSQAoM",
            "YWN0aXZpdHlUeXBlGAIgASgOMiouU0NQRGlzY29yZC5JbnRlcmZhY2UuQm90",
            "QWN0aXZpdHkuQWN0aXZpdHkSFAoMYWN0aXZpdHlUZXh0GAMgASgJIk4KBlN0",
            "YXR1cxILCgdPRkZMSU5FEAASCgoGT05MSU5FEAESCAoESURMRRACEhIKDkRP",
            "X05PVF9ESVNUVVJCEAMSDQoJSU5WSVNJQkxFEAQiYQoIQWN0aXZpdHkSCwoH",
            "UExBWUlORxAAEg0KCVNUUkVBTUlORxABEhAKDExJU1RFTklOR19UTxACEgwK",
            "CFdBVENISU5HEAMSCgoGQ1VTVE9NEAQSDQoJQ09NUEVUSU5HEAViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SCPDiscord.Interface.BotActivity), global::SCPDiscord.Interface.BotActivity.Parser, new[]{ "StatusType", "ActivityType", "ActivityText" }, null, new[]{ typeof(global::SCPDiscord.Interface.BotActivity.Types.Status), typeof(global::SCPDiscord.Interface.BotActivity.Types.Activity) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BotActivity : pb::IMessage<BotActivity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BotActivity> _parser = new pb::MessageParser<BotActivity>(() => new BotActivity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BotActivity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SCPDiscord.Interface.BotActivityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BotActivity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BotActivity(BotActivity other) : this() {
      statusType_ = other.statusType_;
      activityType_ = other.activityType_;
      activityText_ = other.activityText_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BotActivity Clone() {
      return new BotActivity(this);
    }

    /// <summary>Field number for the "statusType" field.</summary>
    public const int StatusTypeFieldNumber = 1;
    private global::SCPDiscord.Interface.BotActivity.Types.Status statusType_ = global::SCPDiscord.Interface.BotActivity.Types.Status.Offline;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SCPDiscord.Interface.BotActivity.Types.Status StatusType {
      get { return statusType_; }
      set {
        statusType_ = value;
      }
    }

    /// <summary>Field number for the "activityType" field.</summary>
    public const int ActivityTypeFieldNumber = 2;
    private global::SCPDiscord.Interface.BotActivity.Types.Activity activityType_ = global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SCPDiscord.Interface.BotActivity.Types.Activity ActivityType {
      get { return activityType_; }
      set {
        activityType_ = value;
      }
    }

    /// <summary>Field number for the "activityText" field.</summary>
    public const int ActivityTextFieldNumber = 3;
    private string activityText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ActivityText {
      get { return activityText_; }
      set {
        activityText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BotActivity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BotActivity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusType != other.StatusType) return false;
      if (ActivityType != other.ActivityType) return false;
      if (ActivityText != other.ActivityText) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusType != global::SCPDiscord.Interface.BotActivity.Types.Status.Offline) hash ^= StatusType.GetHashCode();
      if (ActivityType != global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing) hash ^= ActivityType.GetHashCode();
      if (ActivityText.Length != 0) hash ^= ActivityText.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StatusType != global::SCPDiscord.Interface.BotActivity.Types.Status.Offline) {
        output.WriteRawTag(8);
        output.WriteEnum((int) StatusType);
      }
      if (ActivityType != global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ActivityType);
      }
      if (ActivityText.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ActivityText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StatusType != global::SCPDiscord.Interface.BotActivity.Types.Status.Offline) {
        output.WriteRawTag(8);
        output.WriteEnum((int) StatusType);
      }
      if (ActivityType != global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ActivityType);
      }
      if (ActivityText.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ActivityText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StatusType != global::SCPDiscord.Interface.BotActivity.Types.Status.Offline) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StatusType);
      }
      if (ActivityType != global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActivityType);
      }
      if (ActivityText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityText);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BotActivity other) {
      if (other == null) {
        return;
      }
      if (other.StatusType != global::SCPDiscord.Interface.BotActivity.Types.Status.Offline) {
        StatusType = other.StatusType;
      }
      if (other.ActivityType != global::SCPDiscord.Interface.BotActivity.Types.Activity.Playing) {
        ActivityType = other.ActivityType;
      }
      if (other.ActivityText.Length != 0) {
        ActivityText = other.ActivityText;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusType = (global::SCPDiscord.Interface.BotActivity.Types.Status) input.ReadEnum();
            break;
          }
          case 16: {
            ActivityType = (global::SCPDiscord.Interface.BotActivity.Types.Activity) input.ReadEnum();
            break;
          }
          case 26: {
            ActivityText = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StatusType = (global::SCPDiscord.Interface.BotActivity.Types.Status) input.ReadEnum();
            break;
          }
          case 16: {
            ActivityType = (global::SCPDiscord.Interface.BotActivity.Types.Activity) input.ReadEnum();
            break;
          }
          case 26: {
            ActivityText = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BotActivity message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("OFFLINE")] Offline = 0,
        [pbr::OriginalName("ONLINE")] Online = 1,
        [pbr::OriginalName("IDLE")] Idle = 2,
        [pbr::OriginalName("DO_NOT_DISTURB")] DoNotDisturb = 3,
        [pbr::OriginalName("INVISIBLE")] Invisible = 4,
      }

      public enum Activity {
        [pbr::OriginalName("PLAYING")] Playing = 0,
        [pbr::OriginalName("STREAMING")] Streaming = 1,
        [pbr::OriginalName("LISTENING_TO")] ListeningTo = 2,
        [pbr::OriginalName("WATCHING")] Watching = 3,
        [pbr::OriginalName("CUSTOM")] Custom = 4,
        [pbr::OriginalName("COMPETING")] Competing = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
