//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPDiscord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCPDiscord.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn queue decided.
        ///MTF Epsilon-11 - \&quot;Nine-Tailed Fox\&quot; have arrived at the facility.
        ///Hostile incursion detected, intruders identified as members of hostile GOI \&quot;Chaos Insurgency\&quot;.
        ///Max HP for
        ///set to
        ///SCP settings set.
        ///Round started.
        ///Player attempting connection...
        ///A player has disconnected.
        ///Checking if round has ended...
        ///Round ended after
        ///minutes.
        ///Escaped D-class:    
        ///Rescued Scientists: 
        ///Contained SCPs:     
        ///Killed by SCP:      
        ///Server is ready and waiting for players.
        ///Round is restar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделан выбор очереди на респавн.
        ///МОГ Epsilon-11 - \Девятихвостая Лиса\ прибыли в комплекс.
        ///Обнаружены враждебные элементы, нарушители были идентифицированы как члены враждебной группировки \Повстанцы Хаоса\.
        ///Максимальное кол-во HP для
        ///установлено на
        ///Настройки SCP применены.
        ///Начался новый раунд.
        ///Игрок пытается подключиться к серверу...
        ///Игрок отключился от сервера.
        ///Проверяем закончился ли раунд...
        ///Раунд завершён спустя
        ///минут.
        ///Сбежало Сотруднико Класса D:
        ///Сбежало Научных Сотрудников:
        ///Объектов SCP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
    }
}
